# Generated by Django 4.0.4 on 2022-04-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liberty_loan_database',
            options={'ordering': ['-Full_Name']},
        ),
    ]
